{
    "items": [
      {
        "friendly_name": "mod_tools_file",
        "is_enabled": true,
        "download_link": "https://www.dropbox.com/scl/fi/fatp8vhnc6roed9iarc70/black_ops_one_mod_tool_files.zip?rlkey=eqgpda0ymp7bjr15laptbs8xu&st=sufknfp6&dl=1",
        "extraction_type": "post_converter",
        "description": "",
        "credits": [
          "",
          ""
        ]
      },
      {
        "friendly_name": "game_mod",
        "is_enabled": true,
        "download_link": "https://github.com/Nukem9/LinkerMod/releases/download/v1.3.2/game_mod.zip",
        "extraction_type": "pre_converter",
        "description": "",
        "credits": [
          "",
          ""
        ]
      },
      {
        "friendly_name": "linker_mod",
        "is_enabled": true,
        "download_link": "https://github.com/Nukem9/LinkerMod/releases/download/v1.0.0-r/LinkerMod-1.0.0.zip",
        "extraction_type": "pre_converter",
        "description": "",
        "credits": [
          "",
          ""
        ]
      },
      {
        "friendly_name": "shippuden_map_maker",
        "is_enabled": true,
        "download_link": "https://www.dropbox.com/scl/fi/2p6b2cz0qrx016i1dk5r1/shippuden_map_maker.zip?rlkey=govvk420tcrjnaafygzcj81o5&st=1u148a0h&dl=1",
        "extraction_type": "post_converter",
        "description": "",
        "credits": [
          "",
          ""
        ]
      }
    ]
  }
  